name: Run ERB Linter
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Erb Linter
      uses: revans/erb-action@v0.0.5
      env:
        GITHUB_TOKEN: ${{secrets.github_token}}
