---
name: Code review using Rails Best Practices
author: Money Forward, Inc.
description: Analyze code statically using Rails Best Practices in Github actions
inputs:
  files:
    description: Changes the path to a Rails application
    required: false
  options:
    description: |
      Changes `rails_best_practices` command line options.

      Specify the options in JSON array format.
      e.g.: '["--vendor", "--spec"]'
    required: false
  working_directory:
    description: Changes the current working directory of the Node.js process
    required: false
  reporter_type_notation:
    description: |
      Change the reporter.

      (Multiple can be specified separated by commas)
    required: false
runs:
  using: 'node12'
  main: 'dist/action/index.js'
branding:
  icon: 'search'
  color: 'orange'
