name: Verify
on: [push]

jobs:
  verify:
    uses: setup-rails/setup-rails/.github/workflows/verify.yml@v1
    # uncomment to enable options:
    #
    # with:
    #   brakeman: true
    #   bundler-audit: true
    #   rspec: true
    #   rubocop: true
